spring:
  profiles:
    active: local
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  threads:
    virtual:
      enabled: true

clickhouse:
  host: ${CLICKHOUSE_HOST:localhost}
  port: 8123
  database: default